### PR TITLE
The correct CV bandwidth selection procedure incorporating weights

### PR DESCRIPTION
**Pull request by wxwx1993**
The cross-validation on counter_weights data needs to take weights into account. @jennyjyounglee could you also review the following changes?

### CODE REVIEW

**Comment by Naeemkh** [comment]
Thanks, @wxwx1993. Please update the `NEWS.md` with the changes.

**Comment by Naeemkh** [comment]
Hi @jennyjyounglee could you also review the submitted changes.

**Comment by jennyjyounglee** [comment]
Hi @wxwx1993, I tested again the bandwidth selection of locpol with the updated code. However, now even in the single-level data, the optimal bandwidth selected using KernSmooth and locpol is different where kernel smoothing working better...

**Comment by Naeemkh** [comment]
Hi @wxwx1993 and @jennyjyounglee. Should we merge this PR into the codebase?

**Pull request closed without merging**
